### Site info:
title: HuskyDev
tagline: Yuhan's Blog
author: Yuhan Zhao
email: yuhan-zhao@outlook.com
description: "HuskDev is Yuhan's personal blog." # It will appear in your document head meta and in your feed.xml site description
keywords: "Yuhan, blog, HuskyDev"
baseurl: "/freshman21" # the subpath of your site, e.g. /blog/
url: "https://yulijia.net/freshman21" # the base hostname & protocol for your site

### Personal info and site tools info:
rss_page: true  # enable rss
github_username:  yuhan-zhao
linkedin_page: "https://www.linkedin.com/in/yhzhao"
favicon:     "/assets/images/favicon.ico"
google_analytics_key: UA-57979084-1 # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "True" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_locale: "en" # blog sidebar language set, only include: English (en), Chinese (cn), Japanese (jp), Polish (pl), Korean (kr),  Russian (ru), Turkish (tr), and Indonesian (id).
nav_pages: ["home", "blog", "categories", "research", "projects", "topics"] # pages displayed in navigation bar
nav_topics: ["articles", "Notes", "Optimization", "Deep Learning"] # existing topics


### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge
#plugins: [jekyll-paginate]
#paginate: 5
#paginate_path: "/blog/page:num/"
#excerpt_separator: <!-- more -->
gems:
  - jekyll-paginate-v2
exclude:
  - Gemfile
  - Gemfile.lock

permalink: /:year/:month/:title.html
pagination:
  enabled: true
  per_page: 2
  sort_reverse: true
  title: ':title -page:num'
  trail:
    before: 2
    after: 2 